name: 'Run misspell with reviewdog'
description: '🐶 Run misspell with reviewdog on pull requests to improve code review experience.'
author: 'haya14busa (reviewdog)'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    default: '${{ github.token }}'
  locale:
    description: '-locale flag of misspell. (US/UK)'
    default: ''
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: 'Reporter of reviewdog command [github-pr-check,github-pr-review].'
    default: 'github-pr-check'
  ignore:
    description: 'Comma-separated words to ignore'
    default: ''
  path:
    description: "Base directory to run misspell. Same as `[path]` of `find` command."
    default: '.'
  pattern:
    description: "File patterns of target files. Same as `-name [pattern]` of `find` command."
    default: '*'
  exclude:
    description: "Exclude patterns of target files. Same as `-not -path [exclude]` of `find` command."
    default: ''
  filter_mode:
    description: "Filtering mode for the reviewdog command [added,diff_context,file,nofilter]."
    default: 'added'
  fail_on_error:
    description: "Exit code for reviewdog when errors are found [true,false]."
    default: 'false'

runs:
  using: composite
  steps:
    - run: |
        export COMPOSITE_ROOT="${{ github.action_path }}";
        # The inputs must be MANUALLY SETUP for composite types, Ensure this is kept up to date.
        export INPUT_GITHUB_TOKEN="${{ inputs.github_token }}";
        export INPUT_LOCALE="${{ inputs.locale }}";
        export INPUT_LEVEL="${{ inputs.level }}";
        export INPUT_REPORTER="${{ inputs.reporter }}";
        export INPUT_IGNORE="${{ inputs.ignore }}";
        export INPUT_PATH="${{ inputs.path }}";
        export INPUT_PATTERN="${{ inputs.pattern }}";
        export INPUT_EXCLUDE="${{ inputs.exclude }}";
        export INPUT_FILTER_MODE="${{ inputs.filter_mode }}";
        export INPUT_FAIL_ON_ERROR="${{ inputs.fail_on_error }}";

        FILEPATH="${COMPOSITE_ROOT}/entrypoint.sh"
        if [ -f "$FILEPATH" ]; then
          chmod +x $FILEPATH
          $FILEPATH
        else
          # Exit as not found ( in bash exit code )
          exit 127
        fi
      shell: bash
  
branding:
  icon: 'edit'
  color: 'gray-dark'
